name: terratorch tuning toolkit

on: 
  push:
    branches:
      - main
      - vllm_test
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - 'tests/resources/**'
      - 'examples/**/*'
      - '**/*.svg'
      - '**/*.png'
      - '**/*.txt'
      - '**/*.ipynb'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - 'tests/resources/**'
      - 'examples/**/*'
      - '**/*.svg'
      - '**/*.png'
      - '**/*.txt'
      - '**/*.ipynb'
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    env:
      R_TESTS_VERBOSE: 2
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          #python -m pip install --upgrade pip
          pip install pip==24.2
          pip --version
          pip install -e .[wxc,test]
          # Installing dependencies required to test Galileo (temporary)
          pip install git+https://github.com/Joao-L-S-Almeida/terratorch-galileo.git
      - name: Clean pip cache
        run: pip cache purge
      - name: List pip dependencies
        run: pip list
      - name: Cleaning cache
        run: pip cache purge
      - name: Test with pytest
        run: |
          pytest -s --cov=terratorch -v --cov-report term-missing tests
      - name: Install vLLM dependencies
        run: |
          sudo apt install -y --no-install-recommends ccache git curl wget ca-certificates gcc-12 g++-12 libtcmalloc-minimal4 libnuma-dev ffmpeg libsm6 libxext6 libgl1 jq lsof
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 10 --slave /usr/bin/g++ g++ /usr/bin/g++-12
      - name: Build vLLM
        run: |
          echo "python version: ${{ matrix.python-version }}"
          if [ "${{ matrix.python-version }}" != "3.11" ]; then exit 0; fi
          cd /home/runner/work
          git clone https://github.com/vllm-project/vllm.git
          cd vllm
          # point requirements to local terratorch
          sed -i -e 's/terratorch==.*/-e file:\/\/\/home\/runner\/work\/terratorch\/terratorch/g' requirements/test.txt
          sed -i -e 's/terratorch==.*/-e file:\/\/\/home\/runner\/work\/terratorch\/terratorch/g' requirements/test.in
          pip install uv 
          uv venv
          source .venv/bin/activate
          uv pip install -r requirements/cpu-build.txt --index-strategy unsafe-best-match
          uv pip install -r requirements/cpu.txt --index-strategy unsafe-best-match
          uv pip install -r requirements/lint.txt --index-strategy unsafe-best-match
          VLLM_USE_PRECOMPILED=1 uv pip install .
          uv pip compile requirements/test.in -o requirements/test.txt --index-strategy unsafe-best-match --torch-backend auto
          uv pip install -r requirements/test.txt -f http://download.pytorch.org/whl/torch/ -f https://download.pytorch.org/whl/torchaudio -f https://download.pytorch.org/whl/torchvision
          SKIP=pip-compile pre-commit run --show-diff-on-failure --color=always --all-files --hook-stage manual 


